name: Build and Deploy .NET App

on:
  push:
    branches:
      - main

jobs:
  deploy-to-eriny:
    runs-on: [self-hosted, ErinyDevice]
    
    steps:
      - uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o "./published"

      - name: Deploy to IIS (ERINY)
        shell: powershell
        run: |
          $source = "$(pwd)\published"
          $destination = "C:\Work\SoftwareDevelopment\Deployment\PublishedCleanArchitectured_BloggingPlatform"
          Copy-Item "$source\*" $destination -Recurse -Force
          Write-Host "Deployment done for ERINY runner"
          
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check .NET version
        run: dotnet --version
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o "./published"

      - name: Deploy to IIS
        shell: powershell
        run: |
          $source = "$(pwd)\published"
          $destination = "D:\SingleClic\Software Development\PublishedProject\PublishedBloggingPlatform"
          Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force
          Write-Host "Deployment is Completed Without IIS Reset"
